GET http://localhost:5000/api/users
###

GET http://localhost:5000/api/products
###

GET http://localhost:5000/api/products/bV3n0BzBvr4Plr4bcTQA
###

POST  http://localhost:5000/api/users HTTP/1.1
Content-Type: application/json 
//importante: dejar un espacio en blanco entre la cabecera y el body

{
  "name": "Ernesto Molina",
  "email": "emolina@gmail.com",
  "role": "user"
}
###

POST  http://localhost:5000/api/products HTTP/1.1
Content-Type: application/json 
//importante: dejar un espacio en blanco entre la cabecera y el body

{
  "name": "Media punta adultos",
  "price": 75000,
  "stock": 37,
  "active": true
}

###

DELETE http://localhost:5000/api/products/bV3n0BzBvr4Plr4bcTQA
###

DELETE http://localhost:5000/api/users/1CdqdXnGLabdVeYvATjC